import type { Metadata } from "next";

import "./globals.css";
import "../styles/whatsappBtn.css";
import "../styles/productCard.css";
import FloatingWhatsAppButton from "../components/FloatingWhatsAppButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <FloatingWhatsAppButton />
      </body>
    </html>
  );
}
